apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: uillianhenrique/hello-go:v4.1
          env:
            - name: NAME
              value: "Uillian Henrique"
            - name: AGE
              value: "26"