apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
  - name: goserver-service
    # Porta do service
    port: 80
    # Porta do Container
    targetPort: 8000
    protocol: TCP
    nodePort: 30001 #30000 - 32.767